
- name: Install the package "glusterfs-server"
  apt:
    name: "glusterfs-server"
    state: present
  become: yes

- name: Install the package "lvm2"
  apt:
    name: lvm2
    state: present
  become: yes

- name: Enable glusterfs service
  systemd:
    name: glusterd
    state: started
    enabled: yes
  become: yes
